StringList foo;
StringList bar;
foo = new StringList();
bar = new StringList();
foo.append("Hector");
foo.append("Jorge");
foo.append("Mariana");
foo.append("Irene");
foo.append("Isabel");
foo.append("Gama");
foo.append("Álvaro");
foo.append("José Carlos");
foo.append("David");
foo.append("Cesia");
foo.append("José Juán");
foo.append("Ivonne");
foo.append("Joel");
foo.append("Ate");
foo.append("Janine");
foo.append("Roy");
foo.append("Christian");
foo.append("Denisse");
foo.append("Octavio");
foo.append("Fer");
foo.append("Ángeles");
foo.append("Alonso");
foo.append("Ana Laura");
foo.append("Jesús");
foo.shuffle();

bar.append("Richard Felciano");
bar.append("Butch Rovan");
bar.append("John Cale");
bar.append("Tod Machover");
bar.append("Edgar Varese");
bar.append("Isao Tomita");
bar.append("Aphex Twin");
bar.append("Laurie Spiegel");
bar.append("Reed Ghazala");
bar.append("Toru Takemitsu");
bar.append("Max Mathews");
bar.append("Dj Kool Herc");
bar.append("Autrechre");
bar.append("Boards of Canada");
bar.append("Squarepusher");
bar.append("Kraftwerk");
bar.append("The Glitch Mob");
bar.append("Ben Frost");
bar.append("Dj Shadow");
bar.append("Brian Eno");
bar.append("Nico Muhly");
bar.append("Tim Hecker");
bar.append("Apparat");
bar.append("John Cage");
bar.append("LaMonte Young");
bar.append("Steve Reich");
bar.append("Karlheinz Stockhousen");
bar.append("Alvin Lucier");
bar.append("Pauline Oliveros");
bar.append("Luigi Russolo");
bar.append("Jeff Carey");
bar.append("Laurie Anderson");
bar.append("Jaap Blonk");
bar.append("Pierre Schaeffer");
bar.append("Iannis Xenakis");
bar.append("Ryoji Ikeda");
bar.append("Merzbow");
bar.append("Laetitia Sonami"); 
bar.append("Arvo Part");
bar.append("Philip Glass");
bar.append("Derek Bailey");
bar.append("Keith Rowe");
bar.append("Joan La Barbara");
bar.append("Michel Waisvisz");
bar.append("Neil Harbisson");
bar.append("Zimoun");
bar.append("Peter Vogel");
bar.append("Jean Tinguely");
bar.append("Takuro Mizuta");
bar.append("Nicolas Collins");
bar.append("Conlon Nancarrow");
bar.shuffle();

for (int i =0 ; i<foo.size(); i++){
  print(foo.get(i) + ": ") ;
  print (bar.get(i*2) + " y ");
  println (bar.get(i*2 + 1)); 
}
